---
- name: Install Docker and Docker Compose
  hosts: all
  become: true

  tasks:
    # Update package index
    - name: Update APT package index
      apt:
        update_cache: yes

    # Install prerequisites
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Add Docker GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    # Start and enable Docker service
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    # Add user to Docker group
    - name: Add user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Install Docker Compose
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    # Verify Docker Compose installation
    - name: Verify Docker Compose version
      shell: docker-compose --version
      register: compose_version
      changed_when: false

    # Output Docker Compose version
    - name: Display Docker Compose version
      debug:
        msg: "{{ compose_version.stdout }}"
