---
- name: Deploy Grafana K6 Configuration to Remote Servers
  hosts: all
  become: true
  remote_user: ubuntu

  tasks:
  - name: Check if Docker is installed
    ansible.builtin.command:
      cmd: docker --version
    register: docker_installed
    failed_when: false
    changed_when: false

  - name: setup docker and docker-compose
    ansible.builtin.include_tasks: install-docker.yaml
    # when: docker_installed.rc != 0

  # - name: setup server wordpress
  #   ansible.builtin.include_tasks: wordpress/setup.yaml
  #   when: "'tag_wordpress' in group_names"

  # - name: setup server voteapps
  #   ansible.builtin.include_tasks: voteapps/setup.yaml
  #   when: "'tag_voteapps_server' in group_names"

