---
- name: Deploy Grafana K6 Configuration to Remote Servers
  hosts: tag_testing_server_grafana_k6
  become: true

  vars:
    repository_url: "https://github.com/agungnusako/k6"
    repo_dest: "/opt/k6_repo"
    docker_services: [ "influxdb", "grafana" ]
    load_test_file: "/opt/k6_repo/test/load.js"
    influxdb_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:8086"
    k6_binary_path: "/snap/bin/k6"

  tasks:
  - name: Install Snap if not installed
    ansible.builtin.package:
      name: snapd
      state: present

  - name: Install K6 if not already installed
    ansible.builtin.command:
      cmd: snap list k6
    register: snap_k6_check
    failed_when: false
    changed_when: snap_k6_check.rc != 0

  - name: Install K6 via Snap if not already installed
    ansible.builtin.command:
      cmd: sudo snap install k6
    when: snap_k6_check.rc != 0

  - name: Clone Repository Grafana K6 if not already cloned
    ansible.builtin.git:
      repo: "{{ repository_url }}"
      dest: "{{ repo_dest }}"
      update: no

  - name: Create test directory if it does not exist
    ansible.builtin.file:
      path: "{{ repo_dest }}/test"
      state: directory
      mode: '0755'

  - name: Copy Load Test Script from Template
    ansible.builtin.template:
      src: ./templates/grafana-k6/load.js.j2
      dest: "{{ load_test_file }}"

  - name: Start Docker Compose Services for InfluxDB and Grafana
    ansible.builtin.command:
      cmd: |
        cd "{{ repo_dest }}"
        docker compose up -d {{ docker_services | join(' ') }}
    args:
      executable: /bin/bash

  - name: Run Load Test with K6
    ansible.builtin.shell:
      cmd: |
        cd "{{ repo_dest }}"
        "{{ k6_binary_path }}" run --out influxdb={{ influxdb_url }} {{ load_test_file }}
    args:
      executable: /bin/bash
