- name: Deploy Docker Configuration to Remote Server using synchronize
  hosts: all
  become: true

  tasks:
    - name: Synchronize Docker configuration folder to remote server
      ansible.builtin.synchronize:
        src: /root/seal-batch-7-live-demo/ahmad-ilyas/monitoring/tamplates/monitoring/
        dest: /home/{{ ansible_user }}/monitoring_config/
        mode: push
        recursive: yes

    - name: Ensure Docker Compose is up
      ansible.builtin.shell:
        cmd: |
          docker compose -f /home/{{ ansible_user }}/monitoring_config/docker-compose.yml up -d
      args:
        executable: /bin/bash
