---
- name: Retrieve All Private IP Addresses from Hosts with Specific Tags
  hosts: tag_learnig_monitoring 
  gather_facts: yes

  tasks:
    - name: Debug Retrieved Private IPs
      ansible.builtin.debug:
        msg: "Private IP address of host {{ inventory_hostname }}"
