---
- name: Deploy Grafana K6 Configuration to Remote Servers
  hosts: tag_monitoring_testing_k6, tag_testing_server
  become: true
  gather_facts: true

  tasks:
  - name: Deploy Docker for K6 Environment
    ansible.builtin.include_role:
      name: docker

  - name: Deploy Minikube for Local Kubernetes
    ansible.builtin.include_role:
      name: minikube

  - name: Install kubectl for Kubernetes Management
    ansible.builtin.include_role:
      name: kubectl

  - name: Install Additional Tools (kubectx, kubens)
    ansible.builtin.include_role:
      name: tools

  - name: setup docker and docker-compose
    ansible.builtin.include_tasks: environment.yml
