apiVersion: v1
kind: Service
metadata:
  namespace: voting-apps
  labels:
    app: result
  name: result
spec:
  type: ClusterIP
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
  selector:
    app: result
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: voting-apps
  name: result
  labels:
    name: result
spec:
  ingressClassName: nginx
  rules:
  - host: result.dwyor.xyz
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: result
            port:
              number: 8081