- name: Install kubectx and kubens
  apt:
    name: kubectx
    state: present

- name: Add kubectl alias to bashrc
  lineinfile:
    path: ~/.bashrc
    line: |
      alias k=kubectl
      complete -o default -F __start_kubectl k
  state: present

- name: Reload bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
    warn: false
