---
- name: Deploy Grafana K6 Configuration to Remote Servers
  hosts: tag_rocket_chat_apps, tag_db_mongodb
  become: true
  gather_facts: true
  vars:
    repository_url: "https://github.com/agungnusako/k6"
    repo_dest: "/opt/k6_repo"
    k6_binary_path: "/snap/bin/k6"

  tasks:
  - name: Set private IP from ansible_default_ipv4.address
    set_fact:
      ip_target: "{{ hostvars[groups['tag_rocket_chat_apps'][0]].ansible_default_ipv4.address }}"

  - name: Check if Docker is installed
    ansible.builtin.command:
      cmd: docker --version
    register: docker_installed
    failed_when: false
    changed_when: false

  - name: setup docker and docker-compose
    ansible.builtin.include_tasks: install-docker.yaml
    when: docker_installed.rc != 0

  - name: setup server monitoring
    ansible.builtin.include_tasks: setup-project.yaml
    when: "'tag_rocket_chat_apps' in group_names"

