- name: Checking distro being used
  ansible.builtin.debug:
    msg: "The operating system family is {{ ansible_os_family }}"

# Install Nginx for Debian-based distributions (Ubuntu, Debian, etc.)
- name: Install Nginx on Debian-based systems
  when: ansible_os_family == "Debian"
  apt:
    name: nginx
    state: present
    update_cache: yes

# Install Nginx for RedHat-based distributions (RHEL, CentOS, Fedora, etc.)
- name: Install Nginx on RedHat-based systems
  when: ansible_os_family == "RedHat"
  yum:
    name: nginx
    state: present
    update_cache: yes

# Configure firewall to allow Nginx HTTP and HTTPS traffic
- name: Open HTTP and HTTPS ports in firewall
  ansible.builtin.ufw:
    rule: allow
    name: "{{ item }}"
  loop:
  - 'Nginx HTTP'
  - 'Nginx HTTPS'
  when: ansible_os_family == "Debian"

- name: Open HTTP and HTTPS ports in firewall
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
  - 'http'
  - 'https'
  when: ansible_os_family == "RedHat"

# Ensure Nginx service is started and enabled to run at boot
- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

# Check if Nginx service is running
- name: Check if Nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
  register: nginx_status

- name: Output the status of Nginx service
  ansible.builtin.debug:
    msg: "Nginx service is {{ nginx_status.state }}"
