- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    state: present
  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: present
  become: true

- name: Ensure current user is in the Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Download Docker Compose binary
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false

- name: Verify Docker Compose installation
  ansible.builtin.command: docker-compose --version
  register: docker_compose_version
  changed_when: false
